---
# tasks file for terraform
- name: Get package info to verify if unzip is installed on Debian based systems  # noqa 301 303 305
  shell: apt show unzip
  register: unzip
  ignore_errors: True

- name: Temporarily install unzip currently not in installed state on Debian based systems.
  apt:
    name: unzip
    state: present
    force_apt_get: yes
    update_cache: yes
  when: unzip.rc == 100

- name: Downloading archive for {{ terraform_app }} {{ terraform_version }} temporarily to {{ terraform_dl_loc }} on Debian based systems
  get_url:
    url: "{{ terraform_dl_url }}/{{ terraform_app }}/{{ terraform_version }}/{{ terraform_app }}_{{ terraform_version }}_{{ terraform_osarch }}.zip"
    dest: "{{ terraform_dl_loc }}"

- name: "{{ terraform_app }}_unarchive on Debian based systems."
  unarchive:
    src: "{{ terraform_dl_loc }}/{{ terraform_app }}_{{ terraform_version }}_{{ terraform_osarch }}.zip"
    dest: "{{ terraform_bin_path }}"
    remote_src: true

- name: Uninstalling unzip as it was originally not in installed state on Debian based systems.
  apt:
    name: unzip
    state: absent
    force_apt_get: yes
    update_cache: yes
  when: unzip.rc == 100

- name: "{{ terraform_app }}_archive_removal on Debian based systems."
  file:
    path: "{{ terraform_dl_loc }}/{{ terraform_app }}_{{ terraform_version }}_{{ terraform_osarch }}.zip"
    state: absent
